### PR TITLE
Adding Powershell script to compile Windows installation

### PR DESCRIPTION
**Pull request by jackiecheu**
Trying to create a PowerShell installation script for the Windows systems, based on the original Bash script, as well as adding some details to the readme.md.

### CODE REVIEW

**Comment by maggiepint** [comment]
@jackiecheu - I think you're in pretty good shape here, but please do sign the CLA.

**Comment by mj1856** [comment]
@jackiecheu  - 🏓 ping!  (please sign the CLA)

**Comment by jackiecheu** [comment]
Hi Matt,


Thanks for the following up! However, I believe I signed the CLA a while ago. When I login to the CLA page again today, it said I have signed, see attached screenshot. Is there some other action item I have missed?


Thanks,

Jackie

________________________________

**Comment by mj1856** [comment]
Hmmm...  Maybe try pushing another commit?  Even a one char change just to get the bot to retry.

**Comment by jackiecheu** [comment]
Sure Matt, just re-commit with minor changes from the online editor. Hope it will work this time.


Thanks,

Jackie

________________________________

**Comment by marwahaha** [comment]
@jackiecheu - the issue is that you need to add your email to your Github profile. (I think it's the `jache@microsoft.com` email.)

```
commit edc83249c0b23e49a1eb2e911ac048aad34a2e36
Author: jackiecheu <30635464+jackiecheu@users.noreply.github.com>
Date:   Tue Sep 19 15:58:12 2017 -0700

    Re-attempt to commit by making minor changes

commit 62475271088b5dc73cdd4c62ad929c21a1986ba0
Author: Jackie Cheung <jache@microsoft.com>
Date:   Wed Aug 9 15:44:27 2017 -0700

    Adding Powershell script to compile Windows installation

```

**Comment by marwahaha** [comment]
closing in favor of https://github.com/moment/momentjs.com/pull/554

**Pull request closed without merging**
