### PR TITLE
Add docs for duration weeks

### PR DESCRIPTION
**Pull request by galtalmor**

### CODE REVIEW

**Comment by mj1856** [comment]
This is fine, but it should also somehow talk about how `.weeks()` and `.days()` can overlap.  

Consider:
```javascript
var d = moment.duration(500, 'days');
d.years(); // 1
d.months(); // 4
d.days(); // 13
```
This all adds up.  But:
```javascript
var d = moment.duration(500, 'days');
d.years(); // 1
d.months(); // 4
d.weeks(); // 1
d.days(); // 13
```
It might seem like there are an extra 7 days here, because the number of days doesn't decrease just because you're looking at weeks also.

Not sure how to word this exactly.  Perhaps you can come up with something.

**Comment by galtalmor** [comment]
What do you think of that sentence?

Unlike the other getters for duration, weeks are counted as a subset of the days, and are not taken off the days count.

**Comment by galtalmor** [comment]
@mj1856 ?

**Comment by mj1856** [comment]
Yes, that would work fine.  (sorry for the delayed response)

**Comment by galtalmor** [comment]
@mj1856 Thanks.
I've updated the PR.

**Comment by mj1856** [comment]
Thanks!

**Pull request merged**
