### PR TITLE
Test documentation is runnable with markdown-doctest

### PR DESCRIPTION
**Pull request by Widdershin**
Hello! I'm the author of [markdown-doctest](https://github.com/Widdershin/markdown-doctest).

markdown-doctest runs all of the javascript examples in the documentation to ensure that they at least run without error. The idea is to mimic the experience a user might have when copying and pasting documentation.

As part of setting it up on this repo I found and fixed a few typos 😺.

I have added markdown-doctest to the deploy script so that the documentation will only be deployed if there are no failures. This should ensure that no future typos are introduced and if any breaking changes are made, all relevant pieces of the documentation should be easy to find update.

screen shot 2016-05-02 at 12 54 34 am

Sidenote: markdown-doctest is used by libraries like lodash and RxJS to test their documentation, so it's been proven in the wild.

Let me know what you think 😄.

### CODE REVIEW

**Comment by Widdershin** [comment]
Hello!

I notice that this PR hasn't been actioned. That's okay, I'm in no rush.

I just wanted to state that if this PR isn't for you, that's totally okay.

If you want any clarity or would like anything changed, just let me know.

Cheers 😄

**Comment by maggiepint** [comment]
Well, I asked John-David Dalton from LoDash and he said he likes it so far, so I figure we can merge it in and give it a try.

**Comment by maggiepint** [comment]
Going to fix the merge conflicts and get this one in now.

**Comment by Widdershin** [comment]
Great! I'm happy to resolve any merge conflicts to save you the trouble, if you'd like. Otherwise please just let me know if I can help in any way.

**Comment by maggiepint** [comment]
If you want to resolve, I certainly wouldn't complain. Saves me a lot of screwing around.

**Comment by Widdershin** [comment]
@maggiepint I resolved the conflicts and now `markdown-doctest` is configured to ignore all documentation for plugins. This means that we don't need to add each plugin as a dependency

**Comment by maggiepint** [comment]
Merged before we got merge conflicts again :-)

**Comment by Widdershin** [comment]
Yay! By the way, how would you feel about setting Travis up to run markdown-doctest? That way errors will show up on pull requests prior to merge.

Will save frustration for maintainers as otherwise you might only find about errors when deploying.

I'm happy to configure if you enable Travis for the repo :)

**Comment by Widdershin** [comment]
Oops, temporary brain fart, I see now that Travis is already configured to deploy, and only for master. I wonder if we could keep it like that while also running markdown-doctest for pull requests.

**Comment by maggiepint** [comment]
I agree with this in the docs should probably build on pull request. I'll play with it a bit. I have other stuff I need to do with the build anyways.

**Pull request merged**
