### PR TITLE
Document IANA Etc/GMT* time zone behaviors

### LINKED ISSUE #424: Document IANA Etc/GMT* time zone behaviors
Refer to:
- moment/moment-timezone#277
- moment/moment-timezone#278
- moment/moment-timezone#436
- moment/moment-timezone#191
- moment/moment-timezone#167

Document this as normal behavior in the moment-timezone docs.

### PR DESCRIPTION
**Pull request by h313**
Fixes #424

### CODE REVIEW

**Comment by mj1856** [comment]
Thanks, though a few suggestions for improvement:

- Please point at [this url](https://github.com/eggert/tz/blob/2017b/etcetera#L36-L42) for the IANA explanation.
- Please be clear in terminology.  It's not about `GMT±X`, it's about `Etc/GMT±X`
- Watch case sensitivity.  Be consistent with IANA.
- Since there are more time zones in GMT-1 than `Europe/Madrid`, please clarify.  I'd suggest wording that emphasises the preference for locality based identifiers over fixed-offset identifiers.

**Comment by mj1856** [comment]
Also, please rebase to a single commit. :)

**Comment by mj1856** [comment]
BTW - you don't need to close a PR to make changes.  Just rebase your current branch and push.  It will update the PR automagically. :)

**Comment by mj1856** [comment]
Alternatively, you can just continue to push changes onto this branch without rebasing and I'll just squash-merge when it looks right.  I keep forgetting about that GitHub features. 😉

**Comment by h313** [comment]
Fixed @mj1856

**Comment by h313** [comment]
@mj1856 Is what I have now good?

**Comment by mj1856** [comment]
Yes. :)  Please sign the CLA and I will merge.  Thanks.

**Comment by h313** [comment]
I signed it, but under a different email address. I can't change it on the website?

**Comment by mj1856** [comment]
It needs to be under the same github account you committed with.  If you are signed in, click the details link and it should work.

**Comment by h313** [comment]
It says I signed it already tho

**Comment by mj1856** [comment]
I rebased to update your email address in the commits to match the one on your GitHub profile.

**Pull request merged**
