### PR TITLE
updated doc for moment.min, moment.max

### PR DESCRIPTION
**Pull request by stepancar**
it's possible to pass array of dates to moment.min, moment.max

### CODE REVIEW

**Comment by stepancar** [comment]
[this line in test shows this functionality](https://github.com/moment/moment/blob/develop/src/test/moment/min_max.js#L20)

**Comment by stepancar** [comment]
@mj1856 , check this PR please

**Comment by mj1856** [comment]
It might be clearer why this is useful if the array was loaded into a variable and passed in as a single parameter.

**Comment by stepancar** [comment]
@mj1856 , we can have 30 dates, generated by server. 
its more user friendly to pass 30 dates as one param(array) to moment.min

**Comment by mj1856** [comment]
I agree.  That's why I suggest you illustrate that in the example.  By passing the array in-line, the advantage is not clear.  Just extract the array into a local variable and pass the variable.  Both are correct of course, but this will make it clearer in the docs.

Thanks.

**Comment by stepancar** [comment]
@mj1856 is it good [example](https://github.com/moment/momentjs.com/pull/258/files#diff-1942bf6fe44ffa02fb26c54acf5090c6R18)?

**Comment by stepancar** [comment]
@mj1856 ?

**Comment by mj1856** [comment]
Sorry for the delay.

Yes, that's a good example.  Could you do a similar one for `min` please?  Perhaps just a simple array of numbers there instead of the map, just to have something different.

**Comment by ichernev** [comment]
@stepancar thank you!

**Pull request merged**
