### PR TITLE
Add instructions for building with webpack

### LINKED ISSUE #269: Clarify how to load locales with WebPack
Update the [Loading locales in the browser](https://github.com/moment/momentjs.com/blob/master/docs/moment/06-i18n/04-loading-into-browser.md) section with the info from moment/moment#1435.

Thanks.

### PR DESCRIPTION
**Pull request by iamakulov**
This PR adds a section into docs that clarifies usage with webpack.

I added it after the Browserify section – this place seems the most logical to me.

Closes #269.

### CODE REVIEW

**Comment by iamakulov** [comment]
Hm, Travis triggered a weird error:

```
Error: 
Attempted to require 'moment-locales-webpack-plugin' but was not found in config.
You need to include it in the require section of your .markdown-doctest-setup.js file.

module.exports = {
  require: {
    'moment-locales-webpack-plugin': require('moment-locales-webpack-plugin')
  }
}
```

Why does it trying to require the package? Should I really add that package into the `.markdown-doctest-setup.js` file?

**Comment by marwahaha** [comment]
Thanks for this!

@iamakulov I'm not sure, you could try it and also add it to the `package.json`; the benefit is the code is actually tested to run correctly. Or, I think there's a syntax to `<!-- skip-example -->`.

**Comment by iamakulov** [comment]
@marwahaha Thanks! Added `<!-- skip-example -->` – otherwise, if I add the package into `package.json` and `.markdown-doctest-setup.js`, tests error with

```
Failed - docs/moment/00-use-it/08-webpack.md:20:1
evalmachine.<anonymous>:4
module.exports = {
^

ReferenceError: module is not defined
```

Tests seem to be green now.

**Comment by iamakulov** [comment]
Damn, sorry, missed the notification. Thanks!

**Pull request merged**
