### PR TITLE
Fixes path to the test file

### PR DESCRIPTION
**Pull request by cstuder**
Minor documentation patch.

### CODE REVIEW

**Comment by maggiepint** [comment]
Can you add src to the other path as well? that's what people should be modifying in both cases.

**Comment by cstuder** [comment]
Added the correct second path. I've had overlooked that, thanks for the heads up.

**Comment by maggiepint** [comment]
Any chance on a CLA signature? Would like to merge this.

**Comment by cstuder** [comment]
Sorry, didn't see the missing check. I just signed...

**Pull request merged**
