### PR TITLE
Add moment-hijri to plugins

### PR DESCRIPTION
**Pull request by xsoh**
Can you please add moment-hijri plugin description to  plugins section

### CODE REVIEW

**Comment by xsoh** [comment]
Is there a problem with the request?

**Comment by mj1856** [comment]
Hi @xsoh  - I just stumbled upon this PR.  Sorry it has been sitting for so long!

I have a concern about your plugin.  You use the `h` specifier to indicate a Hijri date, but moment already uses `h` to represent the non-padded hour component of a 12-hour time.

For example, in your readme you show:

```
moment().format('hYYYY/hM/hD');
```

Without your plugin loaded, moment will return `"32015/36/318"` because it's currently 2015-06-18 at 3:00 PM.

I find it a bit concerning to change the output of a function just based on whether or not another library is loaded.  The user may get incorrect numbers just based on a loading error.  It would be better to use a token that is not in use already, perhaps `i` for Islamic or `q` for the q in Umm al-Qura?

**Comment by xsoh** [comment]
@mj1856 alright, we'll discuss that.
 thanks

**Comment by mj1856** [comment]
Thanks!  I'll leave this open for now then.

**Comment by xsoh** [comment]
@mj1856 The specifier has been  updated to `i`.
If there is anything else please tell me and I'll do it straightaway :smile: :+1:

**Comment by mj1856** [comment]
Sorry for the delay.  Merged.

**Pull request merged**
