### PR TITLE
03-string-format.md

### PR DESCRIPTION
**Pull request by rokyed**
added "Please pay attention to capitalization" above all tables.

### CODE REVIEW

**Comment by marwahaha** [comment]
I would prefer a note like 
```
Tokens are case-sensitive.
```

I do not think it merits a markdown header (`#####`).

**Comment by rokyed** [comment]
Long story short, I never seen that and while focusing on something to deliver fast, I omitted that small detail and because of that, we had to redo 2 weeks of work.

**Comment by marwahaha** [comment]
Sorry for your pain. Please make the corrections I mentioned and I think we can merge it.

**Comment by rokyed** [comment]
@marwahaha Done.

**Pull request merged**
