### PR TITLE
add keepLocalTime boolean to .local and .utc

### PR DESCRIPTION
**Pull request by UziTech**
Add signature and description of `moment().local(true)` and `moment().utc(true)`

### CODE REVIEW

**Comment by UziTech** [comment]
@moment @ichernev @marwahaha any feedback? I see on [moment](https://github.com/moment/moment#contributing-) you mention needing co-maintainers. I wouldn't mind helping out.

**Comment by marwahaha** [comment]
Thanks @UziTech . Can you locate when this boolean was added and add it to the docs?

**Comment by UziTech** [comment]
It was added in v2.8.0 https://github.com/moment/moment/blame/16dcad11fd28cad216d2c9f52f5a68dec7201139/moment.js#L2050

where do you want me to add that?

**Comment by UziTech** [comment]
I added the version similar to [`.calendar()`](https://github.com/moment/momentjs.com/blob/master/docs/moment/04-displaying/06-calendar-time.md)

**Comment by marwahaha** [comment]
Great, thanks!

**Pull request merged**
